[tool.pylint.'MESSAGES CONTROL']
max-line-length = 95
disable = "duplicate-code"
ignore = "tests"

[tool.pylint.BASIC]
good-names = [
    "ix",
    "jx",
    "kx",
    "_",
    "df",
    "i",
    "j",
    "k",
    "n",
    "fs",
    "X_w",
    "X_train",
    "X_val",
    "X_test",
    "X"
]

[tool.isort]
multi_line_output  = 3

[tool.mypy]
exclude = [
    "tests/*",
    "^app\\.py$"  # exlcude app.py's to avoid duplicate module name error
]

[tool.bandit]
exclude_dirs = ["tests/"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:past.*:",
    "ignore::DeprecationWarning:pywintypes:"
]

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.coverage.report]
show_missing = true