[tool.pylint.'MESSAGES CONTROL']
max-line-length = 95
disable = "duplicate-code"

[tool.pylint.BASIC]
good-names = ["ix", "jx", "kx", "_", "df", "i", "j", "k", "n", "fs", "X_w", "X_train", "X_val", "X_test", "X_data"]