###
### A complete description of a Prefect Deployment for flow 'Main Model-Building Flow'
###
name: Main Model-Building Flow
description: |-
  This function loads the data, performs a search over the hyperparameters using hyperopt,
  and then trains the best model on the training data and tests it on the test data.
  Finally, it compares the best model from this training to the existing model in
  production (if one exists) and registers and promotes the model to staging if either
  no production model exists or the new model has a better accuracy.

  Args:
    table_name (str): the name of the table in the database that contains the data
    label_col (str): the name of the column in the data that contains the labels
    model_search_json (str): This is the path to the JSON file that contains the model
    name, fixed parameters, and search parameters. Defaults to ./model_search.json
    initial_points_json (Optional[str]): This is the path to the JSON file that
    contains starting points for hyperparameter values for fitting procedure (e.g., to
    use values from previous fit to potentially speed up fitting). Defaults to None
version: 39f1aed134e8bd6e67e8f8e99b195239
# The work queue that will handle this deployment's runs
work_queue_name: scheduled_flow
tags: []
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command:
    - python
    - -m
    - prefect.engine
  stream_output: true

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: Main Model-Building Flow
manifest_path: null
storage: null
path: C:\Users\adamgifford_behavr.DESKTOP-PQU0D8M\Documents\DataScience\PersonalProjects\exercise_prediction\src\orchestration
entrypoint: orchestrate.py:main_flow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    table_name:
      title: table_name
      default: naive_frequency_features
      type: string
    label_col:
      title: label_col
      default: label_group
      type: string
    model_search_json:
      title: model_search_json
      default: ./model_search.json
      type: string
    initial_points_json:
      title: initial_points_json
      type: string
  required: null
  definitions: null
